[book]
authors = ["dr-frmr", "jtneev", "nick1udwig", "bitful-pannul", "willbach", "0x70b1a5", "habsul-rignyr", "commercium-sys", "tadad"]
language = "en"
multilingual = false
src = "src"
title = "Kinode"

[output.html]
edit-url-template = "https://github.com/kinode-dao/kinode-book/edit/main/{path}"

[output.html.fold]
enable = true
level = 1

[output.html.redirect]
"/intro.html" = "/getting_started/intro.html"
"/build_and_deploy_an_app.html" = "/my_first_app/build_and_deploy_an_app.html"
"/install.html" = "/getting_started/install.html"

[output.linkcheck]

[preprocessor.webinclude]

[preprocessor.hide-feature]
